name: razy_mesboub_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.7.0
  image_picker: ^1.0.4
  intl: ^0.17.0
  fl_chart: ^0.66.0
  provider: ^6.1.1
  get_it: ^7.6.4
  iconly: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pic1.png
    - assets/images/pic2.png