// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0xPyLU7u4trw5nXRk5qEBSIZj9TQkKQ',
    appId: '1:205052847187:web:c34f01374aeaebc2eb52a6',
    messagingSenderId: '205052847187',
    projectId: 'razy-mesboub-2-f3f5f',
    authDomain: 'razy-mesboub-2-f3f5f.firebaseapp.com',
    storageBucket: 'razy-mesboub-2-f3f5f.firebasestorage.app',
    measurementId: 'G-BDKV36MGXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3PVQjEjGsPDPdLmypMgY5h9xl6Jz8lg8',
    appId: '1:205052847187:android:66875ada5b5bced6eb52a6',
    messagingSenderId: '205052847187',
    projectId: 'razy-mesboub-2-f3f5f',
    storageBucket: 'razy-mesboub-2-f3f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6FfMgUW_P0DHd2kCBnSrKQgZIYI3Tb8',
    appId: '1:205052847187:ios:0ca686f3dfc1336eeb52a6',
    messagingSenderId: '205052847187',
    projectId: 'razy-mesboub-2-f3f5f',
    storageBucket: 'razy-mesboub-2-f3f5f.firebasestorage.app',
    iosBundleId: 'com.example.razyMesboub2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK6FfMgUW_P0DHd2kCBnSrKQgZIYI3Tb8',
    appId: '1:205052847187:ios:0ca686f3dfc1336eeb52a6',
    messagingSenderId: '205052847187',
    projectId: 'razy-mesboub-2-f3f5f',
    storageBucket: 'razy-mesboub-2-f3f5f.firebasestorage.app',
    iosBundleId: 'com.example.razyMesboub2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt0xPyLU7u4trw5nXRk5qEBSIZj9TQkKQ',
    appId: '1:205052847187:web:25a7020ad1f90f90eb52a6',
    messagingSenderId: '205052847187',
    projectId: 'razy-mesboub-2-f3f5f',
    authDomain: 'razy-mesboub-2-f3f5f.firebaseapp.com',
    storageBucket: 'razy-mesboub-2-f3f5f.firebasestorage.app',
    measurementId: 'G-NMRJ8JW356',
  );
}
